repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: trailing-whitespace
  - id: flake8
- repo: https://github.com/PyCQA/bandit
  rev: master
  hooks:
  - id: bandit
- repo: https://github.com/pre-commit/mirrors-yapf
  rev: master
  hooks:
  - id: yapf